#ifndef UTENTE_H
#define UTENTE_H
#include"rete.h"
#include"profilo.h"

class Utente
{
private:
    Username login;
    Profilo info;
    Rete rete;
public:
    Utente();
    Utente(const Username&);
    Username getLogin() const;
    Profilo getInfo() const;
    Rete getRete() const;
    virtual ~Utente();
};

/*MEGA ONEROSA --> RICERCO SU TUTTO IL DATABASE, QUANDO ELIMINO UTENTE, CERCO SU TUTTE LE RETI
 * FOLLOWING FOLLOWER --> DUE RETI, UNA DOVE HO QUELLI CHE SEGUO E UNA DOVE HO QUELLI CHE MI SEGUONO, COSÌ SI VENGO ELIMINATO, HO LA LISTA DI TUTTI QUELLI CHE MI SEGUO E FACCIO PRESTO
 * ALLA FACEBOOK(CERY) --> AMICIZIE MUTUALI, IO TI SEGUO TU MI SEGUI, IO NON TI SEGUO PIU', TO MARE PUTANA
 * LIST PER RETE
 *
 * COSA SALVARE NELL'XML, NON SI PUÒ SALVARE PUNTATORI
 * -O LOAD AL CARICAMENTO
 * -MI SALVO GLI USERNAME E CARICO SE SERVE
 *
 * LISTA PER COME SALVARE UTENTI (NO SMARTP) PROBABILMENTE LIST FORSE ANCHE SET
 *
 * GERARCHIA DI CLASSI VERTICALI
 *
 *
 */

#endif // UTENTE_H
